export const featuredUniversities = [
    {
      name: "Harvard University",
      country: "United States",
      flag: "🇺🇸",
      ranking: "#1 Global",
      location: "Cambridge, MA",
      established: "1636",
      students: "23,000+",
      acceptance: "3.4%",
      tuition: "$54,880",
      programs: ["Business", "Medicine", "Law", "Engineering", "Liberal Arts"],
      highlights: [
        "Ivy League",
        "Nobel Prize Winners",
        "World-class Faculty",
        "Research Excellence",
      ],
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      name: "University of Oxford",
      country: "United Kingdom",
      flag: "🇬🇧",
      ranking: "#2 Global",
      location: "Oxford, England",
      established: "1096",
      students: "24,000+",
      acceptance: "17.5%",
      tuition: "£28,370",
      programs: ["PPE", "Medicine", "Law", "Engineering", "Humanities"],
      highlights: [
        "Oldest English University",
        "Tutorial System",
        "Historic Colleges",
        "Rhodes Scholarships",
      ],
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      name: "University of Toronto",
      country: "Canada",
      flag: "🇨🇦",
      ranking: "#18 Global",
      location: "Toronto, ON",
      established: "1827",
      students: "97,000+",
      acceptance: "43%",
      tuition: "CAD 58,160",
      programs: [
        "Engineering",
        "Business",
        "Medicine",
        "Computer Science",
        "Arts & Science",
      ],
      highlights: [
        "Top Canadian University",
        "Research Intensive",
        "Diverse Community",
        "Innovation Hub",
      ],
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      name: "University of Melbourne",
      country: "Australia",
      flag: "🇦🇺",
      ranking: "#33 Global",
      location: "Melbourne, VIC",
      established: "1853",
      students: "50,000+",
      acceptance: "70%",
      tuition: "AUD 44,736",
      programs: ["Medicine", "Law", "Business", "Engineering", "Arts"],
      highlights: [
        "Group of Eight",
        "Research Excellence",
        "Beautiful Campus",
        "Cultural Hub",
      ],
      image: "/placeholder.svg?height=200&width=300",
    },
  ];